package com.xxc.domain;

import java.io.Serializable;
import java.util.Date;

public class BackManager implements Serializable {

    private Integer id;
    private String managerId;
    private String managerAccount;
    private String managerPassword;
    private String managerName;
    private String email;
    private String mobile;
    private String managerStatus;
    private String managerMaster;
    private Date createTime;
    private Date updateTime;
    private Date deleteTime;
    private Integer deleteStatus;

    private Role role;
    private RoleBackManager roleBackManager;

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public RoleBackManager getRoleBackManager() {
        return roleBackManager;
    }

    public void setRoleBackManager(RoleBackManager roleBackManager) {
        this.roleBackManager = roleBackManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.id
     *
     * @return the value of tb_backmanager.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.id
     *
     * @param id the value for tb_backmanager.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.manager_id
     *
     * @return the value of tb_backmanager.manager_id
     * @mbggenerated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.manager_id
     *
     * @param managerId the value for tb_backmanager.manager_id
     * @mbggenerated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.manager_account
     *
     * @return the value of tb_backmanager.manager_account
     * @mbggenerated
     */
    public String getManagerAccount() {
        return managerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.manager_account
     *
     * @param managerAccount the value for tb_backmanager.manager_account
     * @mbggenerated
     */
    public void setManagerAccount(String managerAccount) {
        this.managerAccount = managerAccount == null ? null : managerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.manager_password
     *
     * @return the value of tb_backmanager.manager_password
     * @mbggenerated
     */
    public String getManagerPassword() {
        return managerPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.manager_password
     *
     * @param managerPassword the value for tb_backmanager.manager_password
     * @mbggenerated
     */
    public void setManagerPassword(String managerPassword) {
        this.managerPassword = managerPassword == null ? null : managerPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.manager_name
     *
     * @return the value of tb_backmanager.manager_name
     * @mbggenerated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.manager_name
     *
     * @param managerName the value for tb_backmanager.manager_name
     * @mbggenerated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.email
     *
     * @return the value of tb_backmanager.email
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.email
     *
     * @param email the value for tb_backmanager.email
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.mobile
     *
     * @return the value of tb_backmanager.mobile
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.mobile
     *
     * @param mobile the value for tb_backmanager.mobile
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.manager_status
     *
     * @return the value of tb_backmanager.manager_status
     * @mbggenerated
     */
    public String getManagerStatus() {
        return managerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.manager_status
     *
     * @param managerStatus the value for tb_backmanager.manager_status
     * @mbggenerated
     */
    public void setManagerStatus(String managerStatus) {
        this.managerStatus = managerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.manager_master
     *
     * @return the value of tb_backmanager.manager_master
     * @mbggenerated
     */
    public String getManagerMaster() {
        return managerMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.manager_master
     *
     * @param managerMaster the value for tb_backmanager.manager_master
     * @mbggenerated
     */
    public void setManagerMaster(String managerMaster) {
        this.managerMaster = managerMaster == null ? null : managerMaster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_backmanager.create_time
     *
     * @return the value of tb_backmanager.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_backmanager.create_time
     *
     * @param createTime the value for tb_backmanager.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getDeleteTime() {
        return deleteTime;
    }

    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    @Override
    public String toString() {
        return "BackManager{" +
                "id=" + id +
                ", managerId='" + managerId + '\'' +
                ", managerAccount='" + managerAccount + '\'' +
                ", managerPassword='" + managerPassword + '\'' +
                ", managerName='" + managerName + '\'' +
                ", email='" + email + '\'' +
                ", mobile='" + mobile + '\'' +
                ", managerStatus='" + managerStatus + '\'' +
                ", managerMaster='" + managerMaster + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", deleteTime=" + deleteTime +
                ", deleteStatus=" + deleteStatus +
                ", role=" + role +
                ", roleBackManager=" + roleBackManager +
                '}';
    }
}