package com.xxc.domain;

import java.io.Serializable;
import java.util.Date;

public class BatteryStatus implements Serializable {

    private Integer id;
    private String statusId;
    private String batteryStatus;
    private String batteryVoltage;
    private String batteryTemperature;
    private String loadCurrent;
    private String connectStatus;
    private String chargeStatus;
    private String workStatus;
    private Date createTime;
    private Date updateTime;
    private Date deleteTime;
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.id
     *
     * @return the value of tb_batterystatus.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.id
     *
     * @param id the value for tb_batterystatus.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.status_id
     *
     * @return the value of tb_batterystatus.status_id
     * @mbggenerated
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.status_id
     *
     * @param statusId the value for tb_batterystatus.status_id
     * @mbggenerated
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId == null ? null : statusId.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.battery_status
     *
     * @return the value of tb_batterystatus.battery_status
     * @mbggenerated
     */
    public String getBatteryStatus() {
        return batteryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.battery_status
     *
     * @param batteryStatus the value for tb_batterystatus.battery_status
     * @mbggenerated
     */
    public void setBatteryStatus(String batteryStatus) {
        this.batteryStatus = batteryStatus == null ? null : batteryStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.battery_voltage
     *
     * @return the value of tb_batterystatus.battery_voltage
     * @mbggenerated
     */
    public String getBatteryVoltage() {
        return batteryVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.battery_voltage
     *
     * @param batteryVoltage the value for tb_batterystatus.battery_voltage
     * @mbggenerated
     */
    public void setBatteryVoltage(String batteryVoltage) {
        this.batteryVoltage = batteryVoltage == null ? null : batteryVoltage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.battery_temperature
     *
     * @return the value of tb_batterystatus.battery_temperature
     * @mbggenerated
     */
    public String getBatteryTemperature() {
        return batteryTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.battery_temperature
     *
     * @param batteryTemperature the value for tb_batterystatus.battery_temperature
     * @mbggenerated
     */
    public void setBatteryTemperature(String batteryTemperature) {
        this.batteryTemperature = batteryTemperature == null ? null : batteryTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.load_current
     *
     * @return the value of tb_batterystatus.load_current
     * @mbggenerated
     */
    public String getLoadCurrent() {
        return loadCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.load_current
     *
     * @param loadCurrent the value for tb_batterystatus.load_current
     * @mbggenerated
     */
    public void setLoadCurrent(String loadCurrent) {
        this.loadCurrent = loadCurrent == null ? null : loadCurrent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.connect_status
     *
     * @return the value of tb_batterystatus.connect_status
     * @mbggenerated
     */
    public String getConnectStatus() {
        return connectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.connect_status
     *
     * @param connectStatus the value for tb_batterystatus.connect_status
     * @mbggenerated
     */
    public void setConnectStatus(String connectStatus) {
        this.connectStatus = connectStatus == null ? null : connectStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.charge_status
     *
     * @return the value of tb_batterystatus.charge_status
     * @mbggenerated
     */
    public String getChargeStatus() {
        return chargeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.charge_status
     *
     * @param chargeStatus the value for tb_batterystatus.charge_status
     * @mbggenerated
     */
    public void setChargeStatus(String chargeStatus) {
        this.chargeStatus = chargeStatus == null ? null : chargeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.work_status
     *
     * @return the value of tb_batterystatus.work_status
     * @mbggenerated
     */
    public String getWorkStatus() {
        return workStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.work_status
     *
     * @param workStatus the value for tb_batterystatus.work_status
     * @mbggenerated
     */
    public void setWorkStatus(String workStatus) {
        this.workStatus = workStatus == null ? null : workStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.create_time
     *
     * @return the value of tb_batterystatus.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.create_time
     *
     * @param createTime the value for tb_batterystatus.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.update_time
     *
     * @return the value of tb_batterystatus.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.update_time
     *
     * @param updateTime the value for tb_batterystatus.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_batterystatus.delete_time
     *
     * @return the value of tb_batterystatus.delete_time
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_batterystatus.delete_time
     *
     * @param deleteTime the value for tb_batterystatus.delete_time
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    @Override
    public String toString() {
        return "BatteryStatus{" +
                "id=" + id +
                ", statusId='" + statusId + '\'' +
                ", batteryStatus='" + batteryStatus + '\'' +
                ", batteryVoltage='" + batteryVoltage + '\'' +
                ", batteryTemperature='" + batteryTemperature + '\'' +
                ", loadCurrent='" + loadCurrent + '\'' +
                ", connectStatus='" + connectStatus + '\'' +
                ", chargeStatus='" + chargeStatus + '\'' +
                ", workStatus='" + workStatus + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", deleteTime=" + deleteTime +
                ", deleteStatus=" + deleteStatus +
                '}';
    }
}