package com.xxc.domain;

import java.io.Serializable;
import java.util.Date;

public class Permission implements Serializable {

    private Integer id;
    private String perUrl;
    private String perName;
    private Date createTime;
    private Date updateTime;
    private Date deleteTime;
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.id
     *
     * @return the value of tb_permission.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.id
     *
     * @param id the value for tb_permission.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.per_url
     *
     * @return the value of tb_permission.per_url
     * @mbggenerated
     */
    public String getPerUrl() {
        return perUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.per_url
     *
     * @param perUrl the value for tb_permission.per_url
     * @mbggenerated
     */
    public void setPerUrl(String perUrl) {
        this.perUrl = perUrl == null ? null : perUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.per_name
     *
     * @return the value of tb_permission.per_name
     * @mbggenerated
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.per_name
     *
     * @param perName the value for tb_permission.per_name
     * @mbggenerated
     */
    public void setPerName(String perName) {
        this.perName = perName == null ? null : perName.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getDeleteTime() {
        return deleteTime;
    }

    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    @Override
    public String toString() {
        return "Permission{" +
                "id=" + id +
                ", perUrl='" + perUrl + '\'' +
                ", perName='" + perName + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", deleteTime=" + deleteTime +
                ", deleteStatus=" + deleteStatus +
                '}';
    }
}