package com.xxc.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Recharge implements Serializable {

    private Integer id;
    private String rechargeId;
    private String userAccount;
    private BigDecimal price;
    private String payMethod;
    private String payStatus;
    private String orderDetail;
    private Date createTime;
    private Date updateTime;
    private Date deleteTime;
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recharge.id
     *
     * @return the value of tb_recharge.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recharge.id
     *
     * @param id the value for tb_recharge.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recharge.recharge_id
     *
     * @return the value of tb_recharge.recharge_id
     * @mbggenerated
     */
    public String getRechargeId() {
        return rechargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recharge.recharge_id
     *
     * @param rechargeId the value for tb_recharge.recharge_id
     * @mbggenerated
     */
    public void setRechargeId(String rechargeId) {
        this.rechargeId = rechargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recharge.user_account
     *
     * @return the value of tb_recharge.user_account
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recharge.user_account
     *
     * @param userAccount the value for tb_recharge.user_account
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    public String getPayMethod() {
        return payMethod;
    }

    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod;
    }

    public String getPayStatus() {
        return payStatus;
    }

    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus;
    }

    public String getOrderDetail() {
        return orderDetail;
    }

    public void setOrderDetail(String orderDetail) {
        this.orderDetail = orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recharge.insert_time
     *
     * @return the value of tb_recharge.insert_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recharge.insert_time
     *
     * @param createTime the value for tb_recharge.insert_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getDeleteTime() {
        return deleteTime;
    }

    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recharge.money
     *
     * @return the value of tb_recharge.money
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recharge.money
     *
     * @param price the value for tb_recharge.money
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    @Override
    public String toString() {
        return "Recharge{" +
                "id=" + id +
                ", rechargeId='" + rechargeId + '\'' +
                ", userAccount='" + userAccount + '\'' +
                ", price=" + price +
                ", payMethod='" + payMethod + '\'' +
                ", payStatus='" + payStatus + '\'' +
                ", orderDetail='" + orderDetail + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", deleteTime=" + deleteTime +
                ", deleteStatus=" + deleteStatus +
                '}';
    }
}