package com.xxc.domain;

import java.io.Serializable;

public class RoleBackManager implements Serializable {

    private Integer id;
    private Integer roleId;
    private Integer managerId;
    private Integer deleteStatus;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_backmanager.id
     *
     * @return the value of tb_role_backmanager.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_backmanager.id
     *
     * @param id the value for tb_role_backmanager.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_backmanager.role_id
     *
     * @return the value of tb_role_backmanager.role_id
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_backmanager.role_id
     *
     * @param roleId the value for tb_role_backmanager.role_id
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_backmanager.manager_id
     *
     * @return the value of tb_role_backmanager.manager_id
     * @mbggenerated
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_backmanager.manager_id
     *
     * @param managerId the value for tb_role_backmanager.manager_id
     * @mbggenerated
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    @Override
    public String toString() {
        return "RoleBackManager{" +
                "id=" + id +
                ", roleId=" + roleId +
                ", managerId=" + managerId +
                ", deleteStatus=" + deleteStatus +
                '}';
    }
}