package com.xxc.domain;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {

    private Integer id;
    private String managerRole;
    private String roleDetail;
    private Date createTime;
    private Date updateTime;
    private Date deleteTime;
    private Integer deleteStatus;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.id
     *
     * @return the value of tb_role.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.id
     *
     * @param id the value for tb_role.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.manager_role
     *
     * @return the value of tb_role.manager_role
     * @mbggenerated
     */
    public String getManagerRole() {
        return managerRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.manager_role
     *
     * @param managerRole the value for tb_role.manager_role
     * @mbggenerated
     */
    public void setManagerRole(String managerRole) {
        this.managerRole = managerRole == null ? null : managerRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_detail
     *
     * @return the value of tb_role.role_detail
     * @mbggenerated
     */
    public String getRoleDetail() {
        return roleDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_detail
     *
     * @param roleDetail the value for tb_role.role_detail
     * @mbggenerated
     */
    public void setRoleDetail(String roleDetail) {
        this.roleDetail = roleDetail == null ? null : roleDetail.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getDeleteTime() {
        return deleteTime;
    }

    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    @Override
    public String toString() {
        return "Role{" +
                "id=" + id +
                ", managerRole='" + managerRole + '\'' +
                ", roleDetail='" + roleDetail + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", deleteTime=" + deleteTime +
                ", deleteStatus=" + deleteStatus +
                '}';
    }
}