package com.xxc.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Sale implements Serializable {

    private Integer id;
    private String saleId;
    private String userAccount;
    private String batteryId;
    private String status;
    private String payMethod;
    private BigDecimal price;
    private Integer rentalStatus;
    private String orderDetail;
    private Date createTime;
    private Date updateTime;
    private Date deleteTime;
    private Integer deleteStatus;

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sale.id
     *
     * @return the value of tb_sale.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sale.id
     *
     * @param id the value for tb_sale.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sale.sale_id
     *
     * @return the value of tb_sale.sale_id
     * @mbggenerated
     */
    public String getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sale.sale_id
     *
     * @param saleId the value for tb_sale.sale_id
     * @mbggenerated
     */
    public void setSaleId(String saleId) {
        this.saleId = saleId == null ? null : saleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sale.user_id
     *
     * @return the value of tb_sale.user_id
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sale.user_id
     *
     * @param userAccount the value for tb_sale.user_id
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sale.battery_id
     *
     * @return the value of tb_sale.battery_id
     * @mbggenerated
     */
    public String getBatteryId() {
        return batteryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sale.battery_id
     *
     * @param batteryId the value for tb_sale.battery_id
     * @mbggenerated
     */
    public void setBatteryId(String batteryId) {
        this.batteryId = batteryId == null ? null : batteryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sale.status
     *
     * @return the value of tb_sale.status
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sale.status
     *
     * @param status the value for tb_sale.status
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sale.price
     *
     * @return the value of tb_sale.price
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sale.price
     *
     * @param price the value for tb_sale.price
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getPayMethod() {
        return payMethod;
    }

    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod;
    }

    public Integer getRentalStatus() {
        return rentalStatus;
    }

    public void setRentalStatus(Integer rentalStatus) {
        this.rentalStatus = rentalStatus;
    }

    public String getOrderDetail() {
        return orderDetail;
    }

    public void setOrderDetail(String orderDetail) {
        this.orderDetail = orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sale.create_time
     *
     * @return the value of tb_sale.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sale.create_time
     *
     * @param createTime the value for tb_sale.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getDeleteTime() {
        return deleteTime;
    }

    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    @Override
    public String toString() {
        return "Sale{" +
                "id=" + id +
                ", saleId='" + saleId + '\'' +
                ", userAccount='" + userAccount + '\'' +
                ", batteryId='" + batteryId + '\'' +
                ", status='" + status + '\'' +
                ", payMethod='" + payMethod + '\'' +
                ", price=" + price +
                ", rentalStatus=" + rentalStatus +
                ", orderDetail='" + orderDetail + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", deleteTime=" + deleteTime +
                ", deleteStatus=" + deleteStatus +
                ", user=" + user +
                '}';
    }
}